name: 'Runner-to-Runner Worker (Hardcoded IP)'
on:
  workflow_dispatch:

jobs:
  connect:
    runs-on: ubuntu-22.04
    steps:
      - name: Send Message to Listener
        run: |
          # Install ncat to ensure the command is available
          sudo apt-get update && sudo apt-get install -y ncat

          # The listener's IP address, discovered from the other workflow run
          LISTENER_IP="10.1.0.161"
          
          echo "Attempting to send a message to the hardcoded listener at $LISTENER_IP:8080"

          # Use a 10-second timeout (-w 10) in case the listener is not reachable
          # Send a unique message to confirm the connection
          echo "SUCCESS: Connection established from worker runner!" | ncat -v -w 10 $LISTENER_IP 8080
