name: 'Runner-to-Runner Worker'
on:
  workflow_dispatch:

jobs:
  connect:
    runs-on: ubuntu-22.04
    steps:
      - name: Wait and Download IP
        run: |
          # Give the listener a moment to start and upload its artifact
          echo "Waiting for 30 seconds..."
          sleep 30
      
      - name: Download Listener IP Address
        uses: actions/download-artifact@v4
        with:
          name: runner-ip-address
          # This assumes the artifact is from the same repository and workflow run.
          # For cross-repo communication, you would need a more complex setup
          # to share the IP, but for this test, we are assuming they are on the same subnet.

      - name: Send Message to Listener
        run: |
          # Install nmap for ncat
          sudo apt-get update && sudo apt-get install -y nmap

          # Read the listener's IP address from the downloaded file
          LISTENER_IP=$(cat runner_ip.txt)
          echo "Attempting to connect to listener at $LISTENER_IP:8080"

          # Send a message to the listener
          echo "Hello from the worker runner!" | ncat -v $LISTENER_IP 8080
